name: build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      longRunningTests:
        description: Executes the long running tests (including the open_wbo tests) using the release profile
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run long running tests
        if: ${{ inputs.longRunningTests }}
        run: cargo test --release --features long_running_tests open_wbo
